# Generated by Django 5.2.6 on 2026-09-19 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='Fonanyi Holdings Ltd', max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('street', models.CharField(default='Chief Street, Bomaka', max_length=160)),
                ('city', models.CharField(default='Buea, Southwest Region', max_length=120)),
                ('country', models.CharField(default='Cameroon', max_length=80)),
                ('phone_primary', models.CharField(blank=True, max_length=40)),
                ('phone_secondary', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('hours_weekday', models.CharField(default='8am - 6pm', max_length=80)),
                ('hours_saturday', models.CharField(default='8am - 4pm', max_length=80)),
                ('hours_sunday', models.CharField(default='Closed', max_length=80)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('stat_events_covered', models.PositiveIntegerField(default=0)),
                ('stat_solar_installs', models.PositiveIntegerField(default=0)),
                ('stat_workers', models.PositiveIntegerField(default=0)),
                ('stat_countries_sourced', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('role_business', models.CharField(blank=True, max_length=160)),
                ('quote', models.TextField()),
                ('division', models.CharField(choices=[('energy', 'Energy & Rentals'), ('fashion', 'Fashion & Textiles'), ('general', 'General')], default='general', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_featured', models.BooleanField(default=True, help_text='Show on the homepage.')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
