# Generated by Django 5.2.6 on 2026-09-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_dirty', models.BooleanField(default=False)),
                ('last_rebuild_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rebuild flag',
                'verbose_name_plural': 'Rebuild flag',
            },
        ),
    ]
