# Generated by Django 5.2.6 on 2026-09-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0002_contentflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='stat_bookings',
            field=models.PositiveIntegerField(default=0, help_text='Total bookings taken since launch.'),
        ),
    ]
