# Generated by Django 5.2.6 on 2026-09-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0003_sitesettings_stat_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='hours_saturday',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hours_sunday',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hours_weekday',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_closed',
            field=models.CharField(blank=True, default='Monday', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_days',
            field=models.CharField(default='Tuesday - Sunday', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_time',
            field=models.CharField(default='6am - 10pm', max_length=80),
        ),
    ]
