# Generated by Django 5.2.6 on 2026-09-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0004_remove_sitesettings_hours_saturday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='stat_fashion_customers',
            field=models.PositiveIntegerField(default=0, help_text='Customers the boutique has served since 2010.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='stat_bookings',
            field=models.PositiveIntegerField(default=0, help_text='Rental bookings taken since launch: canopies, chairs, tables, service ware, decorations.'),
        ),
    ]
