# Generated by Django 5.2.6 on 2026-09-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0005_sitesettings_stat_fashion_customers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='boutique_hours_closed',
            field=models.CharField(blank=True, default='Sunday & Monday', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='boutique_hours_days',
            field=models.CharField(default='Tuesday - Saturday', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='boutique_hours_time',
            field=models.CharField(default='8am - 7pm WAT', max_length=80),
        ),
    ]
