# Generated by Django 5.2.6 on 2026-09-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0006_sitesettings_boutique_hours_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='division',
            field=models.CharField(choices=[('energy', 'Solar & Electrical'), ('rentals', 'Rentals & Logistics'), ('fashion', 'Fashion & Textiles'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
