# Generated by Django 5.2.6 on 2026-09-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.TextField(blank=True, max_length=400)),
                ('body', models.TextField(help_text='Markdown is rendered by the frontend.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/')),
                ('division', models.CharField(choices=[('energy', 'Energy & Rentals'), ('fashion', 'Fashion & Textiles'), ('company', 'Company News')], default='company', max_length=20)),
                ('author_name', models.CharField(default='Fonanyi Holdings', max_length=120)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('read_minutes', models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['is_published', 'published_at'], name='blog_post_is_publ_9c4b34_idx')],
            },
        ),
    ]
