# Generated by Django 5.2.6 on 2026-09-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_scheduled_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(help_text='Plain text. Leave a blank line between paragraphs; markdown is not rendered.'),
        ),
    ]
