# Generated by Django 5.2.6 on 2026-09-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(help_text='Rich text from the dashboard editor. Plain text is also accepted and is turned into paragraphs when rendered.'),
        ),
    ]
