# Generated by Django 5.2.6 on 2026-09-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(choices=[('events', 'Events & Rentals'), ('energy', 'Solar & Power'), ('fashion', 'Fashion & Textiles'), ('logistics', 'Logistics & Transport')], default='events', max_length=20)),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_published'], name='gallery_gal_categor_15a7d9_idx')],
            },
        ),
    ]
