# Generated by Django 5.2.6 on 2026-09-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('page', 'Page view'), ('link', 'Link click')], default='page', max_length=8)),
                ('path', models.CharField(db_index=True, max_length=300)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('referrer', models.CharField(blank=True, max_length=400)),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', '-created_at'], name='analytics_v_kind_951322_idx')],
            },
        ),
    ]
