# Generated by Django 5.2.6 on 2026-09-21 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitevent',
            name='kind',
            field=models.CharField(choices=[('page', 'Page view'), ('link', 'Link click'), ('form', 'Form submission'), ('login', 'Admin sign-in'), ('login_bad', 'Failed sign-in')], default='page', max_length=10),
        ),
    ]
