# Generated by Django 5.2.6 on 2026-09-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=140)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, help_text='Town or quarter.', max_length=140)),
                ('role', models.CharField(choices=[('canopy', 'Canopy setup crew'), ('driver', 'Driver'), ('solar', 'Solar technician'), ('electrical', 'Electrician'), ('boutique', 'Boutique & sales'), ('other', 'Something else')], default='canopy', max_length=20)),
                ('availability', models.CharField(choices=[('weekends', 'Weekends'), ('weekdays', 'Weekdays'), ('full_time', 'Full time'), ('on_call', 'On call, event by event')], default='on_call', max_length=20)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('about', models.TextField(help_text='What they have done before.')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('hired', 'Hired'), ('declined', 'Declined'), ('archived', 'Archived')], default='new', max_length=12)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='careers_job_status_13e14c_idx')],
            },
        ),
    ]
